/*******************************************************************************
 * Copyright 2017 CPqD. All Rights Reserved.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 ******************************************************************************/
package br.com.cpqd.asr.recognizer.model;

/**
 * This class represents a partial recognition result generated by the speech
 * recognition process.
 * 
 */
public class PartialRecognitionResult {

	/** the speech segment index when operating in continuous mode. */
	private int speechSegmentIndex;

	/** the recognized text. */
	private String text;

	public int getSpeechSegmentIndex() {
		return speechSegmentIndex;
	}

	public void setSpeechSegmentIndex(int speechSegmentIndex) {
		this.speechSegmentIndex = speechSegmentIndex;
	}

	public String getText() {
		return text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Override
	public String toString() {
		return text;
	}

}
